LOAD DATA
INFILE 'F:/WORKING/OMC/2017/VMS/project_Rating/CODE/2017.06.Loader_Rating_Project/loader/DTTT_daily_20161226.csv'
APPEND INTO TABLE billing.load_tmp
FIELDS TERMINATED BY "," TRAILING NULLCOLS
(
COMPANY_ID,
COMPANY_NAME,
MVPN_USERS,
MPBX_USERS,
CONFERENCE_USERS,
MPBX_MAIN_NUMBERS,
BILLING_CYCLE_DAY,
CREATED
)
